default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: story_time_development

test:
  <<: *default
  database: story_time_test

production:
  <<: *default
  database: story_time_production
  username: story_time
  password: <%= ENV['STORY_TIME_DATABASE_PASSWORD'] %>
